import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "../redux/StoreProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Navigation from "@/components/navigation";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Handover app v0.1",
  description: "Generated by create next app",
  icons: {
    rel: "icon",
    icon: "/favicon.png",
    url: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ClerkProvider>
          <StoreProvider>
            <div className="flex w-[100dvw] ">
              <Navigation />
              {children}
            </div>
          </StoreProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
