export const ticketStatus = [
  "In Progress",
  "WFC",
  "Escalated To T2",
  "Resolved",
  "Escalated To CSM",
  "Escalated To RnD",
  "Pending For MW",
  "Pending For RMA",
];

export const maintenanceFields = [
  "pre_scm_summary_total",
  "post_scm_summary_total",
  "pre_scm_summary_total_count",
  "post_scm_summary_total_count",
  "pre_rpd",
  "post_rpd",
  "pre_cm_partial",
  "post_cm_partial",
  "pre_cpe_total_count",
  "post_cpe_total_count",
  "pre_cpe_erouter_count",
  "post_cpe_erouter_count",
  "pre_cpe_cpe_count",
  "post_cpe_cpe_count",
  "pre_cpe_edva_count",
  "post_cpe_edva_count",
  "pre_cpe_emta_count",
  "post_cpe_emta_count",
  "pre_cpe_estb_count",
  "post_cpe_estb_count",
  "pre_cpe_d4_count",
  "post_cpe_d4_count",
  "pre_cpe_d6_count",
  "post_cpe_d6_count",
  "pre_cpe_exclude_d4d6",
  "post_cpe_exclude_d4d6",
];
